// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC__mIX8TXnFBgXsApO2RQRPV8RcrBPyc',
    appId: '1:513369989673:web:d10252dfd62ff290c67238',
    messagingSenderId: '513369989673',
    projectId: 'teachers-app-4540b',
    authDomain: 'teachers-app-4540b.firebaseapp.com',
    storageBucket: 'teachers-app-4540b.appspot.com',
    measurementId: 'G-4998JVJG6F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG4FO5I26hYT7T_nUBDBxPKVtvdrex5jE',
    appId: '1:513369989673:android:4ac7e7e3efea64acc67238',
    messagingSenderId: '513369989673',
    projectId: 'teachers-app-4540b',
    storageBucket: 'teachers-app-4540b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWgYM6Zj-eSOGoC3FH2ehKC5y3rbopujM',
    appId: '1:513369989673:ios:993957ead9b596bdc67238',
    messagingSenderId: '513369989673',
    projectId: 'teachers-app-4540b',
    storageBucket: 'teachers-app-4540b.appspot.com',
    iosBundleId: 'com.example.teachers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWgYM6Zj-eSOGoC3FH2ehKC5y3rbopujM',
    appId: '1:513369989673:ios:993957ead9b596bdc67238',
    messagingSenderId: '513369989673',
    projectId: 'teachers-app-4540b',
    storageBucket: 'teachers-app-4540b.appspot.com',
    iosBundleId: 'com.example.teachers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBC__mIX8TXnFBgXsApO2RQRPV8RcrBPyc',
    appId: '1:513369989673:web:a95843dc9369fbcdc67238',
    messagingSenderId: '513369989673',
    projectId: 'teachers-app-4540b',
    authDomain: 'teachers-app-4540b.firebaseapp.com',
    storageBucket: 'teachers-app-4540b.appspot.com',
    measurementId: 'G-NYEQD5MQ9T',
  );
}
